#!/usr/bin/env bash
max=$1
min=$1
for i in $@
do
	if [[ $i -gt max ]]
	then
		max=$i
	elif [[ $i -lt min ]]
	then
		min=$i
	fi
done


echo "Total arguments are $#"
echo "Max is $max"
echo "Min is $min"
