#!/usr/bin/env bash
echo "Enter an integer:"
read integer
if [[ $integer -gt 0 ]]
then
	for ((i=0;i<=$integer;i++))
	do
		result[i+1]=$i
	done

elif [[ $integer -lt 0 ]] 
then 
	for ((i=0;i<=-($integer);i++))
	do
		let result[i+1]=$integer+$i
	done
fi
echo ${result[*]}
